### ISSUE TITLE
关于具体使用的问题请教

### ISSUE THREAD

**Issue by 1400720231** [tsl0922/sentry-wxwork#1]
首先谢谢您开源您的代码，由于我是刚开始接触docker，我根据您的文档配置好微信相关参数后，启动docker-compose up,但是我在我的sentry web页面的插件地方找不到企业微信，您那边有具体的操作文档么，望回复，respect。

**Comment by tsl0922** [comment]
使用的什么版本的 sentry，最新的 20.x 版本我没测试过，很可能不支持。

**Comment by 1400720231** [comment]
> 使用的什么版本的 sentry，最新的 20.x 版本我没测试过，很可能不支持。

我进去我的容器里面pip list看到sentry是21.1.0，其实我更想知道我安装好sentry-wxwork后webhook那里怎么配置，我callback地址填的是https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token= 但是我没有收到企业微信通知，所以您那边有没有具体的案例给我参考一下，感激了。

**Comment by tsl0922** [comment]
查了下，从 20 版本开始 sentry 就不支持这种插件了（getsentry/onpremise#347），你可能要降级到 10 才能用这个插件。

**Comment by 1400720231** [comment]
> 查了下，从 20 版本开始 sentry 就不支持这种插件了（[getsentry/onpremise#347](https://github.com/getsentry/onpremise/issues/347)），你可能要降级到 10 才能用这个插件。

看了您给的连接，好像是存在版本问题，但是我看他们好像重新build镜像啥的解决了，还是谢谢您的解答，我现在我现在的版本上试试您的插件，如果我解决了会回复您的，当然如果您有成功的案例也希望您分享一下，谢谢。

**Comment by tsl0922** [comment]
我这里几百人天天在用的，只是 sentry 版本是 10，你找找自己的问题吧。使用方法 README 里都已经说了，如果找不到配置的地方，那可能是你的 sentry 版本不兼容这个插件。

**Comment by tsl0922** [comment]
我想起来了，之前应该测试过 20 版本的，虽然能安装插件并且 sentry 启动也可能不会报错，但插件不会被加载的。如果你去看 sentry 官方文档的话，就会发现已经没有 plugin 的章节了，plugin 已经被 Integrations 替代了，但 Integrations 很显然没有 plugin 那么强大。

我已经更新 README，加了对支持 sentry 版本的说明。如果还想用这个插件的话，建议使用 sentry 10，事实上很多公司都还没升级到 20 版本，因为变动太大了，包括底层架构，部署起来也更麻烦了。

**Comment by lizy0329** [comment]
> Integrations

有知道为什么 sentry 采用 Integrations 代替 plugin 的原因吗？

**Comment by lizy0329** [comment]
> 我想起来了，之前应该测试过 20 版本的，虽然能安装插件并且 sentry 启动也可能不会报错，但插件不会被加载的。如果你去看 sentry 官方文档的话，就会发现已经没有 plugin 的章节了，plugin 已经被 Integrations 替代了，但 Integrations 很显然没有 plugin 那么强大。
> 
> 我已经更新 README，加了对支持 sentry 版本的说明。如果还想用这个插件的话，建议使用 sentry 10，事实上很多公司都还没升级到 20 版本，因为变动太大了，包括底层架构，部署起来也更麻烦了。

有知道为什么 sentry 20 采用 Integrations 代替 plugin 的原因吗？
