### ISSUE TITLE
appid不存在

### ISSUE THREAD

**Issue by windhoney** [tsl0922/sentry-wxwork#2]
按文档配置了参数在sentry.conf.py
![image](https://user-images.githubusercontent.com/18001580/114961138-05d69300-9e9b-11eb-95e9-240ca394d661.png)

WXWORK_CORP_ID = 'xxxx'
WXWORK_SECRET = 'xxx'
WXWORK_AGENT_ID = 'xxx'
![image](https://user-images.githubusercontent.com/18001580/114960984-b728f900-9e9a-11eb-99b2-287edae9f671.png)
点配置提示appid不存在，链接地址中没有相关参数
https://open.work.weixin.qq.com/wwopen/sso/qrConnect?redirect_uri=http://192.168.10.10:9111/auth/sso/&state=6b271e0329d74537be4d0c871bfa61ec&agentid=None&appid=None

**Comment by tsl0922** [comment]
sentry 版本？appid 的值来自于 `WXWORK_CORP_ID`, 如果程序没取到，那就说明你的配置没生效。

**Comment by windhoney** [comment]
> sentry 版本？appid 的值来自于 `WXWORK_CORP_ID`, 如果程序没取到，那就说明你的配置没生效。

sentry是10，我重新build了容器之后可以读到了，应该是配置文件修改之后需要build...

**Comment by tsl0922** [comment]
这不是很显然的么，配置会被 copy 到镜像里，每次修改都要 rebuild 并重启容器。
